<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NLayers.BusinessLogic\NLayers.BusinessLogic.csproj" />
    <ProjectReference Include="..\NLayers.Entities\NLayers.Entities.csproj" />
  </ItemGroup>

</Project>
